### PR TITLE
Added RibbonFactory and Decoupled JFrame from JRibbon

### PR DESCRIPTION
**Pull request by erichschroeter**
Quite a few changes (somewhat significant I think), but I've ran the JUnit tests and they pass.
# RibbonFactory

The _RibbonFactory_ as explained in the previous pull request simply implements a builder pattern saving the user from writing a lot of code. I haven't decided the best way to go about supporting the gallery though; it may need a factory for itself _(any thoughts?)_.
# Decoupling JFrame and JRibbon

I didn't see the need to keep _JRibbon_ and _JRibbonFrame_ coupled as there were only a few methods in _JRibbon_ that actually reference _JRibbonFrame_. I chose to mark the constructor and methods as **deprecated** in order to give some releases between dropping the support completely _(I suppose it's up to you to fully deprecate it though)_.

A major reason I wanted to decouple the two classes was because I didn't know how else to nicely allow an application icon to be used on the _JRibbon_ when you don't use the _JRibbonFrame_ class. I am currently working on an application which cannot use the _JRibbonFrame_ as the framework I'm using creates it for me (I'm using JIDE JDAF). I didn't/don't understand why the two classes were coupled in the first place; perhaps you have an explanation. The decoupling is essentially solved by simply deprecating the _JRibbon(JFrame)_ constructor and _getRibbonFrame()_ and eventually just removing those.
# Application Icon

A reference to the ribbon's icon is stored in the _RibbonUI_ **abstract class**, thus giving the ribbon a way to get the application icon without being coupled to a _JRibbonFrame_.

### CODE REVIEW

**Comment by erichschroeter** [comment]
I'm planning on changing the name of RibbonFactory to RibbonBuilder, since it isn't really a factory pattern but rather the builder pattern.

**Comment by shemnon** [comment]
how soon can you have this ready?  I'de like to push a build durring JavaONe

**Comment by shemnon** [comment]
As it stands this will be rejected because it breaks substance....

C:\git\github.com\insubstantial\insubstantial\substance-flamingo\src\main\java\org\pushingpixels\substance\flamingo\ribbon\ui\SubstanceRibbonApplicationMenuButtonUI.java:58: cannot find symbol
symbol  : constructor BasicRibbonApplicationMenuButtonUI()
location: class org.pushingpixels.flamingo.internal.ui.ribbon.appmenu.BasicRibbonApplicationMenuButtonUI
public class SubstanceRibbonApplicationMenuButtonUI extends
       ^
1 error

The symbol it cannot find is the BasicRibbonApplicationMenuButtonUI default constructor.

Should be a simple fix (I hope).

**Comment by erichschroeter** [comment]
Ok, I'll look into it, but I can't guarantee it will be fast. If you want to push a release out, I'd say forget about my pull request for now.

**Comment by shemnon** [comment]
What I may do this weekend is commit the "plumbing" changes needed to enable
the builder, that way we can spin out a different jar that has just the
builder pre 7.1.
On Sep 30, 2011 7:28 PM, "erichschroeter" <
reply@reply.github.com>
wrote:

**Pull request closed without merging**
