### PR TITLE
Added factory for creating a ribbon.

### PR DESCRIPTION
**Pull request by erichschroeter**
Added RibbonFactory along with unit test and usage example. A minor patch to button layout menu tile level classes for checking for null button icons.

The <em>RibbonFactory</em> does not support 100% of the available features had someone manually create a ribbon and its components. The patch to <em>CommandButtonLayoutManagerMenuTileLevel1</em> and <em>CommandButtonLayoutManagerMenuTileLevel2</em> are required for the factory not to error when creating a ribbon application menu item.

I plan on implementing additional features the factory doesn't implement currently incrementally.

### CODE REVIEW

**Comment by shemnon** [comment]
Since I was planning on cutting a release later this week, I won't look into applying this until after I spin the release out.  So that would put it in the Sept 2011 time frame for a release.  Peraps this will give the time to get a more fluent interface for the contextual tab groups.

However, if you want to see the null tolerance code patched in, I would accept a patch consisting of just the code for the null button icons.  This should allow for the existing factory code to work with the June 2011 release without needing to be merged in early.

**Comment by erichschroeter** [comment]
Ok, I'll submit the null tolerance code as a patch.

**Comment by erichschroeter** [comment]
Since I am planning on submitting more code, I'd like to make sure the unit
tests pass prior to submitting. As it is right now, I get 72 failures out of
227 runs, and 3 errors dealing with _IconRibbonBandResizePolicy_. Is this
similar to what you get, or do you run the JUnit test cases?

**Comment by shemnon** [comment]
I run the junits, and they seem to work for me.  I'll reverify here in a bit.

**Pull request closed without merging**
